### ISSUE TITLE
请教作者：视频添加水印有思路吗？

### ISSUE THREAD

**Issue by wkxjc** [huangyz0918/AndroidWM#27]

**Comment by huangyz0918** [comment]
视频和图像的原理是一样的，不过对于视频可能移动设备并不适合，因为计算能力达不到要求。计算高清视频的时间成本过高，还得考虑移动设备内存问题。

**Comment by goopher503** [comment]
谢谢回复。公司要求用户下载视频时给视频添加水印。视频和图像的原理一样是指像图片一样一帧一帧的添加水印吗？我有个设想，就是在视频上面罩一张透明的图片，右下角是水印，不知道可不可行

**Comment by huangyz0918** [comment]
有意思，我觉得是一个不错的 idea。不过按照我的理解，这个更类似于编写一个带有滤镜的视频流播放器？

**Comment by wkxjc** [comment]
类似于视频贴纸

**Comment by huangyz0918** [comment]
如果你要在自己的 App 中添加视频水印，实际上只需要在播放器上面叠加一个 view 就行了。
如果你要把水印写入视频文件中，使视频在其他设备上播放也有水印，则需要将水印编码进实际文件。

一种方式，就是给视频播放器叠加一层 view，之后使用类似与屏幕录制的方式将带有水印的视频保存到本地，虽然这很 tricky，但是这个操作很难保证输出的视频质量，同时不好处理权限问题。

**Comment by wkxjc** [comment]
的确tricky，哈哈，我再想想其他思路，还是得从视频着手。这个库很棒，问题与库无关，关issue了。再次感谢回复
