### ISSUE TITLE
Image upgrade

### ISSUE THREAD

**Issue by carlos815** [huangyz0918/AndroidWM#9]
Hi, I can see that you a simple logo. What do you think about having an image upgrade (A banner for the GitHub project or any other graphics that your app would need).

I can sent you some drafts if you like. I`m thinking about some ideas, I can send you some drafts in a few hours

Let me know what do you think.

**Comment by huangyz0918** [comment]
Yes, it's a simple logo currently. @carlos815 
It's wonderful if you can sent me a better one, you can open a PR for that.

**Comment by huangyz0918** [comment]
I think we don't have the demand now.
